// Hand-rolled equivalent of the file generated by `flutterfire configure`.
// Values pulled from android/app/google-services.json (com.gdg.bridge_k
// client entry) and ios/Runner/GoogleService-Info.plist for the
// `bridge-31f49` Firebase project.
//
// When the project adds web / macOS / windows targets, run
// `flutterfire configure` to regenerate, or hand-add the missing cases.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not configured for Firebase yet — run flutterfire configure '
        'or add a web FirebaseOptions block here.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          '$defaultTargetPlatform is not configured for Firebase yet.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDedWEyHOfp9ls-c9V4ggKC3m9_r8-PFE4',
    appId: '1:413976862252:android:90a03068c0e77b759dbb89',
    messagingSenderId: '413976862252',
    projectId: 'bridge-31f49',
    storageBucket: 'bridge-31f49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyPr8tq6v3FFOYhlQD9KP8J1PhzcT6YIs',
    appId: '1:413976862252:ios:87b1778434254d8d9dbb89',
    messagingSenderId: '413976862252',
    projectId: 'bridge-31f49',
    storageBucket: 'bridge-31f49.firebasestorage.app',
    iosBundleId: 'com.gdg.bridge-k',
  );
}
